"""initial_schema

Revision ID: 83ad5181ce0b
Revises: 
Create Date: 2026-06-23 22:12:12.895166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83ad5181ce0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('affiliate_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('api_platform', sa.String(), nullable=False),
    sa.Column('network_id', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('api_username', sa.String(), nullable=True),
    sa.Column('api_password', sa.String(), nullable=True),
    sa.Column('sub_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipient_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sender_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tracking_url', sa.String(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('payout', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('suggested_subject', sa.String(), nullable=True),
    sa.Column('suggested_from_name', sa.String(), nullable=True),
    sa.Column('html_creative', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_sends_per_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['affiliate_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['recipient_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipients_list_id', 'recipients', ['list_id'], unique=False)
    op.create_index(op.f('ix_recipients_email'), 'recipients', ['email'], unique=False)
    op.create_table('sender_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('proxy_host', sa.String(), nullable=True),
    sa.Column('proxy_port', sa.Integer(), nullable=True),
    sa.Column('proxy_user', sa.String(), nullable=True),
    sa.Column('proxy_pass', sa.String(), nullable=True),
    sa.Column('proxy_geo', sa.String(length=5), nullable=True),
    sa.Column('proxy_type', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('last_send', sa.DateTime(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('daily_sent', sa.Integer(), nullable=False),
    sa.Column('daily_reset_at', sa.DateTime(), nullable=True),
    sa.Column('max_per_day', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['sender_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sender_accounts_email'), 'sender_accounts', ['email'], unique=True)
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_domain'), 'blacklist', ['domain'], unique=False)
    op.create_index(op.f('ix_blacklist_email'), 'blacklist', ['email'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('header_template', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('negative_content', sa.Text(), nullable=True),
    sa.Column('links', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('sleep_between', sa.Integer(), nullable=False),
    sa.Column('max_workers', sa.Integer(), nullable=False),
    sa.Column('send_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('total_filtered', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_data_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppression_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suppression_email_offer', 'suppression_list', ['email', 'offer_id'], unique=False)
    op.create_table('campaign_account_groups',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['sender_groups.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'group_id')
    )
    op.create_table('campaign_recipient_lists',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['recipient_lists.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'list_id')
    )
    op.create_table('send_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mx_server', sa.String(), nullable=True),
    sa.Column('proxy_host', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sender_accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_send_logs_campaign', 'send_logs', ['campaign_id'], unique=False)
    op.create_index('idx_send_logs_status', 'send_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_send_logs_status', table_name='send_logs')
    op.drop_index('idx_send_logs_campaign', table_name='send_logs')
    op.drop_table('send_logs')
    op.drop_table('campaign_recipient_lists')
    op.drop_table('campaign_account_groups')
    op.drop_index('idx_suppression_email_offer', table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_table('offer_data_fields')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_blacklist_email'), table_name='blacklist')
    op.drop_index(op.f('ix_blacklist_domain'), table_name='blacklist')
    op.drop_table('blacklist')
    op.drop_index(op.f('ix_sender_accounts_email'), table_name='sender_accounts')
    op.drop_table('sender_accounts')
    op.drop_index(op.f('ix_recipients_email'), table_name='recipients')
    op.drop_index('idx_recipients_list_id', table_name='recipients')
    op.drop_table('recipients')
    op.drop_table('offers')
    op.drop_table('user_sessions')
    op.drop_table('sender_groups')
    op.drop_table('recipient_lists')
    op.drop_table('affiliate_networks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
